version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask